### ISSUE TITLE
Silent Failure on Transaction Submission

### ISSUE THREAD

**Issue by ghost** [brandedcrate/payjunction-magento#1]
We've been trying to work with a developer using this module and having an issue as described here:

> We are part of the PayJunction Developer network. We are having trouble with the integration of PayJunction with our Magento v1.9 store. We were able to install the module successfully using BrandedCrate's instructions on Github.
> 
> When we attempt to checkout it shows the payment method as PayJunction in the shopping cart. When we click on "Place Order" it attempts to send the order and then nothing happens.
> 
> Our settings for PayJunction in the Magento back-end are as follows:
> 
> PAYJUNCTION CC
> Enabled: YES
> Title: Credit Card (Payjunction.com)
> New order status: Processing
> Payjunction AVS: Address and Zip
> Payjunction CVV: On
> Payjunction Endpoint: live
> Payjunction Password: *******
> Payjunction Username: ********
> Payjunction Appkey: f7a383c0-0635-423b-8391-34ef3e18f01b 

Is there anywhere we might find an error log that will give us more information on why the transaction is silently failing?

**Comment by stevecrozz** [comment]
Every transaction to the payment gateway is logged using Mage::log:
https://github.com/brandedcrate/payjunction-magento/blob/73d254f6e7463b7f7d4814f4591560040ca056d1/app/code/community/Brandedcrate/Payjunction/Model/CreditCard.php#L378

I've found varying methods of toggling the built-in logging facility, so I'm not sure which one to point you to, but it seems the logs are not available unless you are operating in 'developer mode' Can you let me know if you have this already enabled?
http://magebase.com/magento-tutorials/create-your-own-log-files-with-magelog/

**Comment by stevecrozz** [comment]
This seems to be a more complete list of things to do to preparing a magento development environment: http://www.blog.magepsycho.com/configuring-magento-for-development-debug-mode/.

I'll be interested to see if you can capture useful output here. Can you also elaborate on what you mean by 'silent failure'? Does the transaction appear to work and just does not? If you watch the network log with firebug/chrome-dev-tools do you see a server error?

**Comment by stevecrozz** [comment]
I'm going to close this issue for lack of information. Please do reopen if you can confirm you do have logging enabled and you still see no output. You should see entries like if you have logging enabled:
==> var/log/system.log <==
2015-06-25T07:56:55+00:00 DEBUG (7): Payjunction result (id: 1246, code: 00, reason: Approved, amount: 333.24, type: CHARGE, method: HOLD, approvalCode: PJ20AP)
