### ISSUE TITLE
Auto Capture Option

### ISSUE THREAD

**Issue by ghost** [brandedcrate/payjunction-magento#2]
We have a merchant that is requesting that transactions automatically capture in PayJunction rather than putting the transactions on hold until told to capture in Magento. Is this possible, or is there another Order Status that could be included to have Magento do this? Currently the only option is Processing for the New Order Status field in the module settings.

**Comment by stevecrozz** [comment]
This is a feature we could add, but it isn't possible in the current version. I'll take a look and see what it will take to add this.

**Comment by stevecrozz** [comment]
I've added this improvement and released a new version (v0.2.0) which should solve this issue.
