### ISSUE TITLE
Online Refunds Not Implemented?

### ISSUE THREAD

**Issue by ghost** [brandedcrate/payjunction-magento#3]
We have a merchant who needs to be able to issue refunds from Magento. The code to enable this appears to be there, however when I select the purchase invoice and create a credit memo for the refund the only option given is Refund Offline. Is this because refunds are not fully implemented?

![screen shot 2015-07-13 at 2 39 18 pm](https://cloud.githubusercontent.com/assets/9828323/8661589/877bb830-296d-11e5-9c11-7425f0a91099.png)

**Comment by stevecrozz** [comment]
That's right. Refunds are not implemented yet. But that's going on the list now.

**Comment by stevecrozz** [comment]
Refunds are implemented now in v0.3.0: https://github.com/brandedcrate/payjunction-magento/commit/79e4c8ab1acfc1ffb2f4666294768c21ee418342
